version: '3'
services:
  node-app-1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVER=1
    ports:
      - "3001:3000"
    restart: always

  node-app-2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVER=2
    ports:
      - "3002:3000"
    restart: always
  
  node-app-3:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVER=3
    ports:
      - "3003:3000"
    restart: always

  node-app-4:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVER=4
    ports:
      - "3004:3000"
    restart: always

  node-app-5:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVER=5
    ports:
      - "3005:3000"
    restart: always

  node-app-6:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVER=6
    ports:
      - "3006:3000"
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
